## NOMBRE: CARLA JAEL SALINAS MAMANI
## CARRERA: ELECTRONICA
## MATERIA: LAB  DE PROGRAMACION
## RU: 1814673
## CL: 9886540

Lab2) 1 triángulos 2 Vandermonde 3 horner 4 2 ecuaciones 2 incogni
Vence el 2 de marzo de 2022 23:59

Instrucciones
1 Resolución de triángulos  dados 3 datos  tres lados , tres ángulos, 2 lados  1 ángulo ,2 ángulos 1 lado  resolver los otros tres valores  y calcular  el area y superficie del triangulo y medianas

2 Generar matrices enésimas de Vandermonde  y calcular el determinante

3 Realizar la division de polinomios con el método Horner

4 Resolver un sistema de 2 ecuaciones y 2 incógnitas

Para este laboratorio se conformaran grupos de 2 estudiantes , pudiendo trabajar también  en forma individual

aclaracion pregunta 1

https://es.calcprofi.com/calculo-de-triangulo.html

https://www.mathepower.com/es/triangulo.php

https://www.micalculadora.net/matematicas/triangulo-area-lado-anguloe

deben usar ley de senos, ley de cosenos, ley de tangentes


## 1. Resolución de triángulos  dados 3 datos  tres lados , tres ángulos, 2 lados  1 ángulo ,2 ángulos 1 lado  resolver los otros tres valores  y calcular  el area y superficie del triangulo y medianas

In [1]:
import numpy as np
import math


### Caso 1

In [2]:
#Datos un lado y dos angulos

a = float(input('Ingrese el valor del lado a : '))
B = float(input('Ingrese el valor del ángulo B  : ')) 
C = float(input('Ingrese el valor del ángulo C : '))


Ingrese el valor del lado a :  25.2
Ingrese el valor del ángulo B  :  56.32
Ingrese el valor del ángulo C :  38.40


In [5]:
A = 180 - (B+C)
print('El angulo A es igual a = ', A, 'grados')

radian_A = math.radians(A)
radian_B = math.radians(B)
radian_C = math.radians(C)
b = (a*np.sin(radian_B))/(np.sin(radian_A))
print('El lado b es igual a =', np.round(b,3), 'cm')

c = (a*np.sin(radian_C))/(np.sin(radian_A))
print('El lado c es igual a =', np.round(c,3), 'cm')

area = (1/2) *a*b* np.sin(radian_C)
print('El area del triangulo es : ',np.round(area,2))


mediana = np.sqrt(2*(a**2+c**2)-b**2)/2
print('la mediana es igual a : ', np.round(mediana,2))

El angulo A es igual a =  85.28 grados
El lado b es igual a = 21.041 cm
El lado c es igual a = 15.706 cm
El area del triangulo es :  164.68
la mediana es igual a :  18.17


In [6]:
# Caso 2

#Datos dos lados y un angulo comprendido

a = float(input('Ingrese el valor del lado a : '))
b = float(input('Ingrese el valor del lado b : '))

C = float(input('Ingrese el valor del ángulo C : '))


radian_C = math.radians(C)
c = np.sqrt((a**2)+(b**2)-2*(a*b)*np.cos(radian_C))
print('El lado c es igual a =', np.round(c,3), 'cm')

## hallando los angulos
A = ((a*np.sin(radian_C))/c)
A = math.asin((A))*(180/np.pi)
print('El angulo A es igual a = ', np.round(A,2), 'grados')

B = 180 - A - C
print('El angulo B es igual a = ', np.round(B,2), 'grados')

area = (1/2) *a*b* np.sin(radian_C)
print('El area del triangulo es : ',np.round(area,2))


mediana = np.sqrt(2*(a**2+c**2)-b**2)/2
print('la mediana es igual a : ', np.round(mediana,2))

Ingrese el valor del lado a :  10
Ingrese el valor del lado b :  7
Ingrese el valor del ángulo C :  30


El lado c es igual a = 5.268 cm
El angulo A es igual a =  71.63 grados
El angulo B es igual a =  78.37 grados
El area del triangulo es :  17.5
la mediana es igual a :  7.19


In [7]:
# Caso 3, dados tres lados, calcular los angulos


a = float(input('Ingrese el valor del lado a : '))
b = float(input('Ingrese el valor del lado b : '))

c = float(input('Ingrese el valor del lado c : '))



Ingrese el valor del lado a :  15
Ingrese el valor del lado b :  22
Ingrese el valor del lado c :  17


In [8]:
A = (b**2 + c**2 - a**2) / (2 *b*c)

A = math.acos((A))*(180/np.pi)
print('El angulo A es igual a = ', np.round(A,2), 'grados')

B = (a**2 + c**2 - b**2) / (2 *a*c)

B = math.acos((B))*(180/np.pi)
print('El angulo B es igual a = ', np.round(B,2), 'grados')

C = 180 - A - B
print('El angulo C es igual a = ', np.round(C,2), 'grados')
radian_C = np.radians(C)

area = (1/2) *a*b* np.sin(radian_C)
print('El area del triangulo es : ',np.round(area,2))

mediana = np.sqrt(2*(a**2+c**2)-b**2)/2
print('la mediana es igual a : ', np.round(mediana,2))

El angulo A es igual a =  42.89 grados
El angulo B es igual a =  86.63 grados
El angulo C es igual a =  50.48 grados
El area del triangulo es :  127.28
la mediana es igual a :  11.66


In [9]:
## caso 4, 
#dados 3 angulos y el area, calcular los lados

# Caso 3


A = float(input('Ingrese el valor del angulo  A : '))
B = float(input('Ingrese el valor del angulo B : '))

C = float(input('Ingrese el valor del angulo C : '))

area = float(input('Ingrese el valor del area : '))




Ingrese el valor del angulo  A :  30
Ingrese el valor del angulo B :  100
Ingrese el valor del angulo C :  50
Ingrese el valor del area :  19.45


In [11]:
radian_A = np.radians(A)
radian_B = np.radians(B)
radian_C = np.radians(C)

a = (2*area*np.sin(radian_A))/(np.sin(radian_B)*np.sin(radian_C))
a = np.sqrt(a)
print('El lado a es igual a =', np.round(a,2), 'cm')


b = (a*np.sin(radian_B))/(np.sin(radian_A))
print('El lado b es igual a =', np.round(b,2), 'cm')

c = (a*np.sin(radian_C))/(np.sin(radian_A))
print('El lado c es igual a =', np.round(c,2), 'cm')

mediana = np.sqrt(2*(a**2+c**2)-b**2)/2
print('la mediana es igual a : ', np.round(mediana,2))

El lado a es igual a = 5.08 cm
El lado b es igual a = 10.0 cm
El lado c es igual a = 7.78 cm
la mediana es igual a :  4.26


## 2. Generar matrices enésimas de Vandermonde  y calcular el determinante

Para una matriz con numeros consecutivos de 1 a n

In [13]:
import numpy as np


m = int(input('Ingrese el valor de la dimensión de la matriz n : '))
n = m
a = range(1, m+1)
vandermonde_matriz = np.array([a]*n).T**range(n)
print(vandermonde_matriz)

Ingrese el valor de la dimensión de la matriz n :  3


[[1 1 1]
 [1 2 4]
 [1 3 9]]


Para una matriz con valores diferentes (n números ingresados).

In [14]:

a = []
for i in range(n):
    x  = int(input('Ingrese un número x : '))
    a.append(x)
    

Ingrese un número x :  2
Ingrese un número x :  3
Ingrese un número x :  2


In [15]:
vandermonde_matriz = np.array([a]*n).T**range(n)
print(vandermonde_matriz)

[[1 2 4]
 [1 3 9]
 [1 2 4]]


### Calcular el determinante

In [16]:
def determinant_recursive(A, total=0):
    # almacenar índices en la lista para llamar a las filas
    indices = list(range(len(A)))
   
    if len(A) == 2 and len(A[0]) == 2:
        val = A[0][0] * A[1][1] - A[1][0] * A[0][1]
        return val
 
    # define una sub matriz para enfocarse en cada columna
    for fc in indices: # para cada columna
        # encontramos una sub matriz
        As = A#realiza una copia de la matriz
        As = As[1:] # elimina la primera fila
        n_largo = len(As) # obtenemos la dimension n 
 
        for i in range(n_largo): 
            # 
            As[i] = list(As[i][0:fc]) + list(As[i][fc+1:] )
 
        signo = (-1) ** (fc % 2) # asigna el signo
        # pasamos la sub matriz recursivamente nuevamente al mismo método 
        sub_det = determinant_recursive(As)
        # sumar todos los retornos de la recursividad
        total += signo * A[0][fc] * sub_det 
 
    return total

In [17]:
A = list(vandermonde_matriz)  
Det = determinant_recursive(A)
npDet = np.linalg.det(A)
print("La determinante de la matriz A es", round(Det,9))
print("La determinante de la matriz A según la librería de numpy es ", round(npDet,9))



La determinante de la matriz A es 0
La determinante de la matriz A según la librería de numpy es  0.0


## 3

In [19]:
import numpy as np
#Polinomio 1
#Valor de x
#Coeficientes del polinomio

numero_coeficientes_p1 = int(input('Ingrese el numero de coeficientes del polinomio 1'))
coef_polinomio_1 = []
coef_polinomio_2 = []
for m in range(numero_coeficientes_p1):
    a = int(input('Ingrese un coeficiente del del polinomio 1'))
    print(a)
    coef_polinomio_1.append(a)
print('polinomio 1 ', coef_polinomio_1)
numero_coeficientes_p2 = int(input('Ingrese el numero de coeficientes del polinomio 2'))

for m in range(numero_coeficientes_p2):
    a = int(input('Ingrese un coeficiente del del polinomio 2'))
    
    coef_polinomio_2.append(a)


print(coef_polinomio_1, coef_polinomio_2)


Ingrese el numero de coeficientes del polinomio 1 5
Ingrese un coeficiente del del polinomio 1 12


12


Ingrese un coeficiente del del polinomio 1 -7


-7


Ingrese un coeficiente del del polinomio 1 -74


-74


Ingrese un coeficiente del del polinomio 1 -7


-7


Ingrese un coeficiente del del polinomio 1 16


16
polinomio 1  [12, -7, -74, -7, 16]


Ingrese el numero de coeficientes del polinomio 2 3
Ingrese un coeficiente del del polinomio 2 3
Ingrese un coeficiente del del polinomio 2 -7
Ingrese un coeficiente del del polinomio 2 -4


[12, -7, -74, -7, 16] [3, -7, -4]


In [20]:
coef_polinomio_1, coef_polinomio_2

([12, -7, -74, -7, 16], [3, -7, -4])

In [22]:

resultado=0
divisor =np.array(coef_polinomio_2[1:])
divisor = -1*divisor
resto = coef_polinomio_1[len(coef_polinomio_1)-(len(coef_polinomio_2)-1):]

primer_cociente = coef_polinomio_2[0]
print('divisor ', divisor)
print('resto ', resto)
print('primer cociente ',primer_cociente)


divisor  [7 4]
resto  [-7, 16]
primer cociente  3


In [23]:
resultado_escalera = 0
coef_cocientes = []
nuevo_valor = [coef_polinomio_1[0]]
#Recorrer los coeficientes
lista = []
nuevo_valor = coef_polinomio_1[0]
nueva_lista = []
for i in range(len(coef_polinomio_1)-len(resto)):
    
    resultado = nuevo_valor / primer_cociente
    coef_cocientes.append(resultado)
    print('coef_cocientes',coef_cocientes)
    sumatoria = []
    for j in range(len(divisor)):
        
        valor = divisor[j]*coef_cocientes[i]
        nueva_lista.append(valor)
        
    print('nueva_lista',nueva_lista)
    sumatoria_valor = coef_polinomio_1[i+1]
    
    for k in range(len(nueva_lista)-len(divisor)+1):
        print('sumas')
        print(sumatoria_valor, nueva_lista[k])
        sumatoria_valor = sumatoria_valor + nueva_lista[k]

        print('sumatoria .... ', sumatoria_valor)
        
    print('sumatoria valor', sumatoria_valor)
    if i == (len(coef_polinomio_1)-len(resto))-1:
        break
        
    nuevo_valor = sumatoria_valor
    nueva_lista = nueva_lista[i+1:]
    print('nueva_lista final ', nueva_lista)
    print('======')

    

coef_cocientes [4.0]
nueva_lista [28.0, 16.0]
sumas
-7 28.0
sumatoria ....  21.0
sumatoria valor 21.0
nueva_lista final  [16.0]
coef_cocientes [4.0, 7.0]
nueva_lista [16.0, 49.0, 28.0]
sumas
-74 16.0
sumatoria ....  -58.0
sumas
-58.0 49.0
sumatoria ....  -9.0
sumatoria valor -9.0
nueva_lista final  [28.0]
coef_cocientes [4.0, 7.0, -3.0]
nueva_lista [28.0, -21.0, -12.0]
sumas
-7 28.0
sumatoria ....  21.0
sumas
21.0 -21.0
sumatoria ....  0.0
sumatoria valor 0.0


In [25]:
print('los coeficientes finales ', coef_cocientes)

los coeficientes finales  [4.0, 7.0, -3.0]


In [26]:
nueva_lista_resto = nueva_lista
nuevo_divisor = divisor
coef_resto_resultado = []
for i in range(len(resto)):
    
    coef_resto_valor = resto[i]
    
    for j in range(len(resto)):
        
        coef_resto_valor = coef_resto_valor + nueva_lista_resto[j]
        
        print('coef_resto_valor nuevo',coef_resto_valor)
        
        if len(nueva_lista_resto)==1:
            
            break
    
    coef_resto_resultado.append(coef_resto_valor)
    nueva_lista_resto = nueva_lista_resto[len(resto):]
    
    print('=====')

coef_resto_valor nuevo 21.0
coef_resto_valor nuevo 0.0
=====
coef_resto_valor nuevo 4.0
=====


In [29]:
print('los valores del resto final es ' , coef_resto_resultado)

los valores del resto final es  [0.0, 4.0]


In [31]:
#Valor de x
x= int(input('Ingrese el valor de x '))
#Coeficientes del polinomio
coeficientes=coef_cocientes

resultado=0
#Recorrer los coeficientes
for i in range(0,len(coeficientes)):
    #Multiplicar al valor parcial el valor de x más el coeficiente
    resultado= resultado * x + coeficientes[i]

suma_resto = 0
suma_resto = np.array(coef_resto_resultado).sum()

    
print("Resultado: "+str(resultado), 'con resto ', suma_resto)


Ingrese el valor de x  3


Resultado: 54.0 con resto  4.0


### 4.

ax + by = c 

dx + ey = f


In [32]:

a = int(input('Ingrese el valor de a '))
b = int(input('Ingrese el valor de b '))
c = int(input('Ingrese el valor de c '))
d = int(input('Ingrese el valor de d '))
e = int(input('Ingrese el valor de e '))
f = int(input('Ingrese el valor de f '))

det = a * e - b * d

if det != 0 :
    x = (e * c - b * f) / det
    y = (a * f - d * c) / det

    print ("La solucion al sistema es x=", x, "e y=", y)

else :
    m = d / a

    if m * c == f :
        print ("El sistema tiene infinitas soluciones")
    else:
        print ("El sistema no tiene soluciones")
        
        

Ingrese el valor de a  1
Ingrese el valor de b  2
Ingrese el valor de c  3
Ingrese el valor de d  4
Ingrese el valor de e  5
Ingrese el valor de f  6


La solucion al sistema es x= -1.0 e y= 2.0
